
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web:
    restart: on-failure
    build: ./web
    hostname: web1
    ports:
      - '5000:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'

